[metadata]
name = bifrost
version = 0.0.3
author = Sankalpa Adhikari
author_email = sankalpa2522@gmail.com
description = Command line tool that helps you to create, update, deploy, redeploy, delete forms in Kobo-toolbox.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/sankalpa-adhikari-sa/Kobo-bifrost-cli
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[options]
packages = find:
python_requires = >=3.8
install_requires =
    typer
    keyring
    pandas
    requests
    openpyxl
    xlsxwriter
    secretstorage
    rich

[options.extras_require]
dev =
    pytest>=7.0
    mypy
    flake8
    black
    tox
    types-requests
    pandas-stubs

[options.entry_points]
console_scripts =
    bifrost = bifrost_cli.bifrost:app

[flake8]
max-line-length = 120
extend-ignore = E203, W503
exclude =
    .tox,
    .git,
    __pycache__,
    build,
    dist,
    *.pyc,
    *.egg-info,
    .eggs

[isort]
profile = black
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
line_length = 88
